//
// Created by Jack Davidson on 20/07/2020.
//

#ifndef INC_3D_GRAPHICS_AND_ANIMATION_COURSEWORK_2018_PROFILERWINDOW_H
#define INC_3D_GRAPHICS_AND_ANIMATION_COURSEWORK_2018_PROFILERWINDOW_H


void DrawProfilerWindow();

#endif //INC_3D_GRAPHICS_AND_ANIMATION_COURSEWORK_2018_PROFILERWINDOW_H
